Traceback (most recent call last):
  File "/home/teeriaho/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/teeriaho/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/teeriaho/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/teeriaho/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/teeriaho/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/teeriaho/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/teeriaho/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/teeriaho/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from jupyterquiz import display_quiz

display_quiz('mchoice2.json')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_16903/1762506311.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0mjupyterquiz[0m [0;32mimport[0m [0mdisplay_quiz[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mdisplay_quiz[0m[0;34m([0m[0;34m'mchoice2.json'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/mynewbook/jupyterquiz/dynamic.py[0m in [0;36mdisplay_quiz[0;34m(ref, num, shuffle_questions, shuffle_answers)[0m
[1;32m     76[0m             [0;31m#print("File detected")[0m[0;34m[0m[0;34m[0m[0m
[1;32m     77[0m             [0mscript[0m [0;34m+=[0m [0;34mf"var questions{div_id}="[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 78[0;31m             [0;32mwith[0m [0mopen[0m[0;34m([0m[0mref[0m[0;34m)[0m [0;32mas[0m [0mfile[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     79[0m                 [0;32mfor[0m [0mline[0m [0;32min[0m [0mfile[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     80[0m                     [0mscript[0m [0;34m+=[0m [0mline[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'mchoice2.json'
FileNotFoundError: [Errno 2] No such file or directory: 'mchoice2.json'

